repos:
  - repo: local
    hooks:
      - id: terraform-fmt-check
        name: Terraform fmt check
        entry: terraform
        args: [fmt, -check, -diff]
        language: system
        files: \.tf$
        pass_filenames: false
        
      - id: terraform-validate
        name: Terraform validate
        entry: terraform
        args: [validate]
        language: system
        files: \.tf$
        pass_filenames: false
        require_serial: true
        
      - id: tfsec
        name: tfsec security scan
        entry: tfsec
        args: [.]
        language: system
        files: \.tf$
        pass_filenames: false
        require_serial: true